---
##### CI for use by github no need for action to be added
##### https://pre-commit.com/hooks.html
##### Inherited
ci:
  autofix_prs: false
  skip:
    # This steps run in the ci workflow. Keep in sync
    - mypy
    - pylint

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - -L vm_clockify
          - --ignore-words-list=ihs,ro,fo,tage
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types:
          - csv
          - json

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Safety
      - id: detect-private-key

      # git checks
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict

      # General checks
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: mixed-line-ending
      # - id: name-tests-test

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
          - prettier-plugin-sort-json@3.0.1
        exclude_types:
          - python

  # Scan for passwords
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.3
    hooks:
      - id: gitleaks

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1 # or higher tag
    hooks:
      - id: yamllint

  # PYTHON ---------------------------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=130
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        args:
          - --config=./pyproject.toml
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=pyproject.toml
        additional_dependencies: ["bandit[toml]"]

  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      # - id: mypy
      #   name: Check with mypy
      #   entry: scripts/run-in-env.sh mypy
      #   language: script
      #   types:
      #     - python
      #   require_serial: true
      #   exclude: ^tests/.+
      - id: pylint
        name: Check with pylint
        entry: scripts/run-in-env.sh pylint
        language: script
        types:
          - python
        require_serial: true
        exclude: ^tests/.+
