---
# Pre-commit configuration
# For details, visit: https://pre-commit.com/hooks.html

ci:
  autofix_prs: false
  skip:
    # These steps run in the CI workflow. Keep in sync.
    - mypy
    - pylint

default_language_version:
  python: python3.12

repos:
  # Codespell for spelling corrections
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - -L vm_clockify
          - --ignore-words-list=ihs,ro,fo,tage,astroid
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types:
          - csv
          - json

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: mixed-line-ending

  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-sort-json@3.1.0
        exclude_types:
          - python

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

  # YAML Linting
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  # Python-specific hooks ######################################################
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args:
          - --fix
          - --unsafe-fixes
          - --line-length=130
          - --exit-non-zero-on-fix
      - id: ruff-format
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [--py313-plus]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=pyproject.toml
        additional_dependencies: ["bandit[toml]"]

  # Local hooks for mypy and pylint
  - repo: local
    hooks:
      - id: mypy
        name: Run Mypy in Virtualenv
        entry: scripts/run-in-env.sh mypy
        language: script
        types: [python]
        require_serial: true
        exclude: ^tests/.+
      - id: pylint
        name: Run Pylint in Virtualenv
        entry: scripts/run-in-env.sh pylint
        language: script
        types: [python]
        require_serial: true
        exclude: ^tests/.+
