---
##### CI for use by github no need for action to be added
##### Inherited
ci:
  autofix_prs: false
  skip:
    # This steps run in the ci workflow. Keep in sync
    - ansible-lint
    - mypy
    - pylint

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - -L vm_clockify
          - --ignore-words-list=ihs,ro,fo
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types:
          - csv
          - json

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Safety
      - id: detect-private-key

      # git checks
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: no-commit-to-branch
      #   args: [--branch, main]

      # General checks
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
          - prettier-plugin-sort-json@3.0.1
        exclude_types:
          - python

  # Scan for passwords
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0 # or higher tag
    hooks:
      - id: yamllint

  # PYTHON ---------------------------------------------------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - --line-length=130
        <<: &python-files-with-tests
          files: ^((vm_clockify|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=130
          - --ignore=E203,W503
        additional_dependencies:
          - flake8-docstrings==1.7.0
          - pydocstyle==6.3.0
        <<: &python-files
          files: ^(vm_clockify/.+)?[^/]+\.py$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=bandit.yml
        <<: *python-files-with-tests
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=130
          - --filter-files

  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      - id: mypy
        name: Check with mypy
        entry: scripts/run-in-env.sh mypy
        language: script
        types:
          - python
        require_serial: true
        <<: *python-files
      - id: pylint
        name: Check with pylint
        entry: scripts/run-in-env.sh pylint
        language: script
        types:
          - python
        require_serial: true
        <<: *python-files
