version: "3.8"

services:
  ##############################################################################
  ##############################################################################
  ##############################################################################
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2021}
        VERSION: ${VERSION:-latest}

        PROJECT_NAME: ${PROJECT_NAME:-vm_clockify}
        VERSION: ${VERSION:-0.0.1}
        ENV_MODE: ${ENV_MODE:-PROD}
        LOGGING_LEVEL: ${LOGGING_LEVEL:-DEBUG}
        LOGGING_VERBOSE: ${LOGGING_VERBOSE:-2}
    image: mvladislav/vm-clockify:${VERSION:-latest}
    stdin_open: true # docker run -i
    tty: true # docker run -t
    env_file: .env
    volumes:
      - ./scan/:/vm-clockify/scan/
    #   - ./app/:/vm-clockify/app/
    command: vm_clockify
    networks:
      default: {}
    restart: always

################################################################################
################################################################################
################################################################################
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
