name: Python code quality and tests

on:
  push:
    branches:
      - main
  pull_request:

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

env:
  DEFAULT_PYTHON: "3.12"
  PROJECT_PATH: "vm_clockify"

jobs:
  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
      - name: Install dependencies
        run: |
          python3 -m pip install .
          python3 -m pip install .[dev]
      # Following steps cannot run by pre-commit.ci as repo = local
      - name: Run mypy
        run: mypy ${{ env.PROJECT_PATH }}/
      - name: Pylint review
        run: pylint ${{ env.PROJECT_PATH }}/

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
      - name: Install dependencies
        run: |
          python3 -m pip install .
          python3 -m pip install .[dev]
      - name: Run pytest
        run: pytest --cov=./ --cov-report=xml --junitxml=pytest-report.xml --cov-fail-under=80

      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: pytest-report.xml

      # - name: Upload coverage results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-results
      #     path: coverage.xml
